name: Node.js CI
on:
  schedule:
    - cron:  '* */1 * * *'
jobs:
  aasem:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          AAA=$(date)
          echo $AAA
          echo "$AAA" > sss
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "jamikon" 
          git push
          sleep 2s
